FROM docker.io/rocm/pytorch:rocm7.1.1_ubuntu22.04_py3.11_pytorch_release_2.10.0

RUN git clone https://github.com/HPE/torch-hammer.git

WORKDIR torch-hammer

RUN chmod +x torch-hammer.py \
    && pip install -r requirements.txt  \
    && pip install amdsmi

ENTRYPOINT ["/torch-hammer/torch-hammer.py"]
