FROM nvcr.io/nvidia/pytorch:26.02-py3

RUN git clone https://github.com/HPE/torch-hammer.git

WORKDIR /workspace/torch-hammer

RUN chmod +x torch-hammer.py \
    && pip install -r requirements.txt \
    && pip install nvidia-ml-py

ENTRYPOINT ["/workspace/torch-hammer/torch-hammer.py"]
